name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Prepare deployment files
        run: |
          # Copy static files
          cp index.html dist/
          cp -r src/styles dist/styles
          
          # Update paths in index.html for production
          sed -i 's|<script type="module" src="./src/main.ts"></script>|<script type="module" src="./main.js"></script>|g' dist/index.html
          sed -i 's|href="./src/styles/index.css"|href="./styles/index.css"|g' dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
